### ISSUE TITLE
Caching seems to crash

### ISSUE THREAD

**Issue by rickybiscus** [romanvm/script.module.simpleplugin#20]
Hey; 

my addon [plugin.video.auvio](https://github.com/rickybiscus/plugin.video.auvio) seems to crash when caching is enabled (and I need it so the addon does not request the API each time a virtual folder is opened).

It seems to work on Linux Mint but breaks when I use LibreElec.

It seems that there is a bug [when caching data](https://github.com/rickybiscus/plugin.video.auvio/blob/master/lib/api.py#L148) using 

    @plugin.cached()

Here's the end of the kodi.log (which grows to about 50 Mo!)

    2021-05-15 10:37:22.617 T:1265    ERROR <general>: plugin.video.auvio [v.3.2.2]: **** End diagnostic info ****
    2021-05-15 10:37:22.622 T:1265    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                        - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                       Error Type: <class 'UnicodeDecodeError'>
                                                       Error Contents: 'ascii' codec can't decode byte 0xe5 in position 1: ordinal not in range(128)
                                                       Traceback (most recent call last):
                                                         File "/storage/.kodi/addons/plugin.video.auvio/main.py", line 690, in <module>
                                                           common.plugin.run()
                                                         File "/storage/.kodi/addons/plugin.video.auvio/lib/simpleplugin.py", line 1095, in run
                                                           result = self._resolve_function()
                                                         File "/storage/.kodi/addons/plugin.video.auvio/lib/simpleplugin.py", line 1356, in _resolve_function
                                                           return route.func(**kwargs)
                                                         File "/storage/.kodi/addons/plugin.video.auvio/main.py", line 223, in menu_channels
                                                           datas = api.get_menu_channels()
                                                         File "/storage/.kodi/addons/plugin.video.auvio/lib/api.py", line 54, in get_menu_channels
                                                           app_datas = get_app_settings()
                                                         File "/storage/.kodi/addons/plugin.video.auvio/lib/simpleplugin.py", line 822, in inner_wrapper
                                                           with self.get_storage('__cache__.pcl') as cache:
                                                         File "/storage/.kodi/addons/plugin.video.auvio/lib/simpleplugin.py", line 744, in get_storage
                                                           return Storage(self.profile_dir, filename)
                                                         File "/storage/.kodi/addons/plugin.video.auvio/lib/simpleplugin.py", line 239, in __init__
                                                           self._storage = pickle.loads(contents)
                                                       UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 1: ordinal not in range(128)
                                                       -->End of Python script error report<--

Do you know what this could be ?

Thanks a lot.

([this issue](https://github.com/rickybiscus/plugin.video.auvio/issues/22) may be related too)

**Comment by rickybiscus** [comment]
It looks like it's me that changed the encoding of the data.
Thus it was crashing when loading the old data.
Removing the file `$HOME/.kodi/userdata/addon_data/plugin.video.auvio/__cache__.pcl` fixed it.  
Sorry !
