### ISSUE TITLE
Error storage feature (has no attribute 'new_datetime')

### ISSUE THREAD

**Issue by SylvainCecchetto** [romanvm/script.module.simpleplugin#9]
Hi,

We are using your framework since the beginning of our add-on [Catch Up TV & More](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore).
Is it very nice and helpful! Thanks.

But we have two users who encounter errors on Android and Windows platform. It seems that this error isn't related to our plugin. 

Furthermore, after a fresh Kodi installation without any other add-on installed, the error come only after a few days.

```python
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                         - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'new_datetime'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 334, in <module>
                                                common.PLUGIN.run(window_title)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 779, in run
                                                result = action_callable(params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 260, in channel_entry
                                                return channel.channel_entry(params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/groupecanal.py", line 85, in channel_entry
                                                return root(params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 431, in inner_wrapper
                                                with self.get_storage('__cache__.pcl') as cache:
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 409, in get_storage
                                                return Storage(self.config_dir, filename)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 102, in __init__
                                                self._storage = pickle.loads(contents)
                                            AttributeError: 'module' object has no attribute 'new_datetime'
                                            -->End of Python script error report<--
```

Thank you for your help.

**Comment by romanvm** [comment]
Which version of Kodi are you running? I know that there was problem with `datetime` module in some Kodi versions for some platforms.

**Comment by SylvainCecchetto** [comment]
The version 17.5.
So problem seems to be related to Kodi ?

**Comment by romanvm** [comment]
Yes, Python Standard Library inside some Kodi instances seems to have broken `datetime` module. I've thought of switching to POSIX time and `time` module but it would break compatibility with existing cache files.

**Comment by SylvainCecchetto** [comment]
Oh ok, thank you for your lights about this Kodi issue.
In our case we only used Mem_Storage for cache (RAM). 
So, if I understand, I can translate all the datetime stuff in simpleplugin.py to the time module and just a restart of Kodi will clear all the cache files and it will be Ok?

**Comment by romanvm** [comment]
Yes, you can calculate time intervals for cache storage using POSIX time in seconds instead of `datetime` classes, so you convert respective code if you know what you are doing. I cannot give you 100% guarantee but I haven't heard of any problems with `time` module in Kodi so far.

I guess I will convert that too in the next version of SimplePluign when I find some free time that is hard for me now.

**Comment by SylvainCecchetto** [comment]
Ok, I will try to do that. Thank you very much for the informations!

I sympathize for the missing "free time" ... ;-)
